/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RecommendationTag = IDL.Variant({
  'okay' : IDL.Null,
  'recommended' : IDL.Null,
  'notRecommended' : IDL.Null,
});
export const MacroNutrients = IDL.Record({
  'fat' : IDL.Float64,
  'carbs' : IDL.Float64,
  'salt' : IDL.Float64,
  'sugar' : IDL.Float64,
  'protein' : IDL.Float64,
  'cholesterol' : IDL.Float64,
});
export const FoodLogEntry = IDL.Record({
  'loggedTimestamp' : IDL.Int,
  'recommendationTag' : RecommendationTag,
  'calories' : IDL.Nat,
  'servingSize' : IDL.Text,
  'macros' : MacroNutrients,
  'foodName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Goal = IDL.Variant({
  'other' : IDL.Null,
  'gain' : IDL.Null,
  'lose' : IDL.Null,
  'maintain' : IDL.Null,
});
export const ExerciseFrequency = IDL.Variant({
  'three' : IDL.Null,
  'twice' : IDL.Null,
  'none' : IDL.Null,
  'once' : IDL.Null,
  'fourPlus' : IDL.Null,
});
export const Profile = IDL.Record({
  'weight' : IDL.Float64,
  'goal' : Goal,
  'exerciseFrequency' : ExerciseFrequency,
  'birthday' : IDL.Text,
  'gender' : IDL.Text,
  'ingredientAvoidances' : IDL.Vec(IDL.Text),
  'dailyCalorieTarget' : IDL.Nat,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFoodLogEntry' : IDL.Func([FoodLogEntry], [], []),
  'analyzeFood' : IDL.Func([IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteFoodLogEntry' : IDL.Func([IDL.Int], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFoodLogsByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(FoodLogEntry)],
      ['query'],
    ),
  'getProfile' : IDL.Func([], [Profile], ['query']),
  'getTotalCaloriesToday' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'getWeeklyCalorieHistory' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'saveProfile' : IDL.Func([Profile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateDailyCalorieTarget' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RecommendationTag = IDL.Variant({
    'okay' : IDL.Null,
    'recommended' : IDL.Null,
    'notRecommended' : IDL.Null,
  });
  const MacroNutrients = IDL.Record({
    'fat' : IDL.Float64,
    'carbs' : IDL.Float64,
    'salt' : IDL.Float64,
    'sugar' : IDL.Float64,
    'protein' : IDL.Float64,
    'cholesterol' : IDL.Float64,
  });
  const FoodLogEntry = IDL.Record({
    'loggedTimestamp' : IDL.Int,
    'recommendationTag' : RecommendationTag,
    'calories' : IDL.Nat,
    'servingSize' : IDL.Text,
    'macros' : MacroNutrients,
    'foodName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Goal = IDL.Variant({
    'other' : IDL.Null,
    'gain' : IDL.Null,
    'lose' : IDL.Null,
    'maintain' : IDL.Null,
  });
  const ExerciseFrequency = IDL.Variant({
    'three' : IDL.Null,
    'twice' : IDL.Null,
    'none' : IDL.Null,
    'once' : IDL.Null,
    'fourPlus' : IDL.Null,
  });
  const Profile = IDL.Record({
    'weight' : IDL.Float64,
    'goal' : Goal,
    'exerciseFrequency' : ExerciseFrequency,
    'birthday' : IDL.Text,
    'gender' : IDL.Text,
    'ingredientAvoidances' : IDL.Vec(IDL.Text),
    'dailyCalorieTarget' : IDL.Nat,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFoodLogEntry' : IDL.Func([FoodLogEntry], [], []),
    'analyzeFood' : IDL.Func([IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteFoodLogEntry' : IDL.Func([IDL.Int], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFoodLogsByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(FoodLogEntry)],
        ['query'],
      ),
    'getProfile' : IDL.Func([], [Profile], ['query']),
    'getTotalCaloriesToday' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'getWeeklyCalorieHistory' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'saveProfile' : IDL.Func([Profile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateDailyCalorieTarget' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };