/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExerciseFrequency = { 'three' : null } |
  { 'twice' : null } |
  { 'none' : null } |
  { 'once' : null } |
  { 'fourPlus' : null };
export interface FoodLogEntry {
  'loggedTimestamp' : bigint,
  'recommendationTag' : RecommendationTag,
  'calories' : bigint,
  'servingSize' : string,
  'macros' : MacroNutrients,
  'foodName' : string,
}
export type Goal = { 'other' : null } |
  { 'gain' : null } |
  { 'lose' : null } |
  { 'maintain' : null };
export interface MacroNutrients {
  'fat' : number,
  'carbs' : number,
  'salt' : number,
  'sugar' : number,
  'protein' : number,
  'cholesterol' : number,
}
export interface Profile {
  'weight' : number,
  'goal' : Goal,
  'exerciseFrequency' : ExerciseFrequency,
  'birthday' : string,
  'gender' : string,
  'ingredientAvoidances' : Array<string>,
  'dailyCalorieTarget' : bigint,
  'lastName' : string,
  'firstName' : string,
}
export type RecommendationTag = { 'okay' : null } |
  { 'recommended' : null } |
  { 'notRecommended' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFoodLogEntry' : ActorMethod<[FoodLogEntry], undefined>,
  'analyzeFood' : ActorMethod<[string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteFoodLogEntry' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFoodLogsByDateRange' : ActorMethod<[bigint, bigint], Array<FoodLogEntry>>,
  'getProfile' : ActorMethod<[], Profile>,
  'getTotalCaloriesToday' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getWeeklyCalorieHistory' : ActorMethod<[], Array<bigint>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'saveProfile' : ActorMethod<[Profile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateDailyCalorieTarget' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];