/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MacroNutrients {
    fat: number;
    carbs: number;
    salt: number;
    sugar: number;
    protein: number;
    cholesterol: number;
}
export interface FoodLogEntry {
    loggedTimestamp: bigint;
    recommendationTag: RecommendationTag;
    calories: bigint;
    servingSize: string;
    macros: MacroNutrients;
    foodName: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Profile {
    weight: number;
    goal: Goal;
    exerciseFrequency: ExerciseFrequency;
    birthday: string;
    gender: string;
    ingredientAvoidances: Array<string>;
    dailyCalorieTarget: bigint;
    lastName: string;
    firstName: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum ExerciseFrequency {
    three = "three",
    twice = "twice",
    none = "none",
    once = "once",
    fourPlus = "fourPlus"
}
export enum Goal {
    other = "other",
    gain = "gain",
    lose = "lose",
    maintain = "maintain"
}
export enum RecommendationTag {
    okay = "okay",
    recommended = "recommended",
    notRecommended = "notRecommended"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addFoodLogEntry(entry: FoodLogEntry): Promise<void>;
    analyzeFood(foodDescription: string): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteFoodLogEntry(timestamp: bigint): Promise<void>;
    getCallerUserProfile(): Promise<Profile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFoodLogsByDateRange(startDate: bigint, endDate: bigint): Promise<Array<FoodLogEntry>>;
    getProfile(): Promise<Profile>;
    getTotalCaloriesToday(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<Profile | null>;
    getWeeklyCalorieHistory(): Promise<Array<bigint>>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: Profile): Promise<void>;
    saveProfile(profile: Profile): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateDailyCalorieTarget(newTarget: bigint): Promise<void>;
}
import type { ExerciseFrequency as _ExerciseFrequency, FoodLogEntry as _FoodLogEntry, Goal as _Goal, MacroNutrients as _MacroNutrients, Profile as _Profile, RecommendationTag as _RecommendationTag, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addFoodLogEntry(arg0: FoodLogEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFoodLogEntry(to_candid_FoodLogEntry_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFoodLogEntry(to_candid_FoodLogEntry_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async analyzeFood(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeFood(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeFood(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteFoodLogEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFoodLogEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFoodLogEntry(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFoodLogsByDateRange(arg0: bigint, arg1: bigint): Promise<Array<FoodLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodLogsByDateRange(arg0, arg1);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodLogsByDateRange(arg0, arg1);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_Profile_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_Profile_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalCaloriesToday(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalCaloriesToday();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalCaloriesToday();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklyCalorieHistory(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyCalorieHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyCalorieHistory();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: Profile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_Profile_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_Profile_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveProfile(arg0: Profile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProfile(to_candid_Profile_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProfile(to_candid_Profile_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateDailyCalorieTarget(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDailyCalorieTarget(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDailyCalorieTarget(arg0);
            return result;
        }
    }
}
function from_candid_ExerciseFrequency_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExerciseFrequency): ExerciseFrequency {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_FoodLogEntry_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FoodLogEntry): FoodLogEntry {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Goal_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Goal): Goal {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_RecommendationTag_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecommendationTag): RecommendationTag {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : from_candid_Profile_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    loggedTimestamp: bigint;
    recommendationTag: _RecommendationTag;
    calories: bigint;
    servingSize: string;
    macros: _MacroNutrients;
    foodName: string;
}): {
    loggedTimestamp: bigint;
    recommendationTag: RecommendationTag;
    calories: bigint;
    servingSize: string;
    macros: MacroNutrients;
    foodName: string;
} {
    return {
        loggedTimestamp: value.loggedTimestamp,
        recommendationTag: from_candid_RecommendationTag_n19(_uploadFile, _downloadFile, value.recommendationTag),
        calories: value.calories,
        servingSize: value.servingSize,
        macros: value.macros,
        foodName: value.foodName
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: number;
    goal: _Goal;
    exerciseFrequency: _ExerciseFrequency;
    birthday: string;
    gender: string;
    ingredientAvoidances: Array<string>;
    dailyCalorieTarget: bigint;
    lastName: string;
    firstName: string;
}): {
    weight: number;
    goal: Goal;
    exerciseFrequency: ExerciseFrequency;
    birthday: string;
    gender: string;
    ingredientAvoidances: Array<string>;
    dailyCalorieTarget: bigint;
    lastName: string;
    firstName: string;
} {
    return {
        weight: value.weight,
        goal: from_candid_Goal_n10(_uploadFile, _downloadFile, value.goal),
        exerciseFrequency: from_candid_ExerciseFrequency_n12(_uploadFile, _downloadFile, value.exerciseFrequency),
        birthday: value.birthday,
        gender: value.gender,
        ingredientAvoidances: value.ingredientAvoidances,
        dailyCalorieTarget: value.dailyCalorieTarget,
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    gain: null;
} | {
    lose: null;
} | {
    maintain: null;
}): Goal {
    return "other" in value ? Goal.other : "gain" in value ? Goal.gain : "lose" in value ? Goal.lose : "maintain" in value ? Goal.maintain : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    three: null;
} | {
    twice: null;
} | {
    none: null;
} | {
    once: null;
} | {
    fourPlus: null;
}): ExerciseFrequency {
    return "three" in value ? ExerciseFrequency.three : "twice" in value ? ExerciseFrequency.twice : "none" in value ? ExerciseFrequency.none : "once" in value ? ExerciseFrequency.once : "fourPlus" in value ? ExerciseFrequency.fourPlus : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    okay: null;
} | {
    recommended: null;
} | {
    notRecommended: null;
}): RecommendationTag {
    return "okay" in value ? RecommendationTag.okay : "recommended" in value ? RecommendationTag.recommended : "notRecommended" in value ? RecommendationTag.notRecommended : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FoodLogEntry>): Array<FoodLogEntry> {
    return value.map((x)=>from_candid_FoodLogEntry_n17(_uploadFile, _downloadFile, x));
}
function to_candid_ExerciseFrequency_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExerciseFrequency): _ExerciseFrequency {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_FoodLogEntry_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FoodLogEntry): _FoodLogEntry {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Goal_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Goal): _Goal {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_Profile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Profile): _Profile {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_RecommendationTag_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecommendationTag): _RecommendationTag {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    loggedTimestamp: bigint;
    recommendationTag: RecommendationTag;
    calories: bigint;
    servingSize: string;
    macros: MacroNutrients;
    foodName: string;
}): {
    loggedTimestamp: bigint;
    recommendationTag: _RecommendationTag;
    calories: bigint;
    servingSize: string;
    macros: _MacroNutrients;
    foodName: string;
} {
    return {
        loggedTimestamp: value.loggedTimestamp,
        recommendationTag: to_candid_RecommendationTag_n3(_uploadFile, _downloadFile, value.recommendationTag),
        calories: value.calories,
        servingSize: value.servingSize,
        macros: value.macros,
        foodName: value.foodName
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: number;
    goal: Goal;
    exerciseFrequency: ExerciseFrequency;
    birthday: string;
    gender: string;
    ingredientAvoidances: Array<string>;
    dailyCalorieTarget: bigint;
    lastName: string;
    firstName: string;
}): {
    weight: number;
    goal: _Goal;
    exerciseFrequency: _ExerciseFrequency;
    birthday: string;
    gender: string;
    ingredientAvoidances: Array<string>;
    dailyCalorieTarget: bigint;
    lastName: string;
    firstName: string;
} {
    return {
        weight: value.weight,
        goal: to_candid_Goal_n23(_uploadFile, _downloadFile, value.goal),
        exerciseFrequency: to_candid_ExerciseFrequency_n25(_uploadFile, _downloadFile, value.exerciseFrequency),
        birthday: value.birthday,
        gender: value.gender,
        ingredientAvoidances: value.ingredientAvoidances,
        dailyCalorieTarget: value.dailyCalorieTarget,
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Goal): {
    other: null;
} | {
    gain: null;
} | {
    lose: null;
} | {
    maintain: null;
} {
    return value == Goal.other ? {
        other: null
    } : value == Goal.gain ? {
        gain: null
    } : value == Goal.lose ? {
        lose: null
    } : value == Goal.maintain ? {
        maintain: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExerciseFrequency): {
    three: null;
} | {
    twice: null;
} | {
    none: null;
} | {
    once: null;
} | {
    fourPlus: null;
} {
    return value == ExerciseFrequency.three ? {
        three: null
    } : value == ExerciseFrequency.twice ? {
        twice: null
    } : value == ExerciseFrequency.none ? {
        none: null
    } : value == ExerciseFrequency.once ? {
        once: null
    } : value == ExerciseFrequency.fourPlus ? {
        fourPlus: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecommendationTag): {
    okay: null;
} | {
    recommended: null;
} | {
    notRecommended: null;
} {
    return value == RecommendationTag.okay ? {
        okay: null
    } : value == RecommendationTag.recommended ? {
        recommended: null
    } : value == RecommendationTag.notRecommended ? {
        notRecommended: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
